#!/usr/bin/env node
/**
 * Turns the raw body-map SVG in the repo root into a typed data module.
 *
 * The source file stacks two full-body drawings in the same 660×1206 viewBox:
 * the back view first, then the front view painted on top. This splits them
 * into separate front/back path sets so the app can show them side by side.
 *
 * Run: node scripts/build-bodymap.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(__dirname, "..", "..", "body_muscle_visulaizer_active.txt");
const OUT = join(__dirname, "..", "src", "data", "bodymap.ts");

const svg = readFileSync(SOURCE, "utf8");

/** Pull every <g id="…">…</g> block in document order. */
function groups(source) {
  const found = [];
  const open = /<g id="([^"]+)"([^>]*)>/g;
  let match;
  while ((match = open.exec(source))) {
    // Groups here never nest, so the next </g> closes this one.
    const end = source.indexOf("</g>", match.index);
    found.push({
      id: match.group ?? match[1],
      attrs: match[2],
      body: source.slice(match.index + match[0].length, end),
    });
  }
  return found;
}

const all = groups(svg).map((group) => ({
  ...group,
  paths: [...group.body.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]),
}));

// The first `body` silhouette ends the back view; everything after is the front.
const splitAt = all.findIndex((group) => group.id === "body");
const back = all.slice(0, splitAt + 1);
const front = all.slice(splitAt + 1);

/** Joint markers ship hidden in the source — drop them entirely. */
const isHidden = (group) => group.attrs.includes('class="hidden"');

function collect(list) {
  const muscles = {};
  let silhouette = [];
  for (const group of list) {
    if (isHidden(group) || group.paths.length === 0) continue;
    if (group.id === "body") {
      silhouette = group.paths;
      continue;
    }
    muscles[group.id] = (muscles[group.id] ?? []).concat(group.paths);
  }
  return { muscles, silhouette };
}

const backData = collect(back);
const frontData = collect(front);

const serialise = (value) => JSON.stringify(value, null, 2);

writeFileSync(
  OUT,
  `// Generated by scripts/build-bodymap.mjs — do not edit by hand.
export const BODY_VIEWBOX = "0 0 660.46 1206.46";

export type BodyView = {
  /** Grey base drawing of the figure. */
  silhouette: string[];
  /** Muscle id → the paths that make it up. */
  muscles: Record<string, string[]>;
};

export const BODY_FRONT: BodyView = ${serialise(frontData)};

export const BODY_BACK: BodyView = ${serialise(backData)};

export const FRONT_MUSCLES = Object.keys(BODY_FRONT.muscles);
export const BACK_MUSCLES = Object.keys(BODY_BACK.muscles);
`,
);

console.log(`front: ${Object.keys(frontData.muscles).join(", ")}`);
console.log(`back:  ${Object.keys(backData.muscles).join(", ")}`);
console.log(`→ ${OUT} (${(readFileSync(OUT).length / 1024).toFixed(0)} KB)`);
